### ISSUE TITLE
Weirdly colored overlay on right side of file

### ISSUE THREAD

**Issue by hyoretsu** [justinschmitz97/avif.io#100]
When I convert an image, I get an overlay line.
![image](https://user-images.githubusercontent.com/20804322/204946027-9fc52aec-b608-490f-ae33-d96059432a54.png)
I'm using 100% Effort, 100% Quality and Keep transparency. This is the original image.
![4 - Unrivaled Fresh Fruit (Normal)](https://user-images.githubusercontent.com/20804322/204946048-6b57a9a6-5fc6-4828-a9d6-323a90487b3a.png)

This also happens when using [ShortPixel](https://shortpixel.com/online-image-compression). I'm using the latest version of Microsoft Edge (also tried on Opera GX, same thing).

**Comment by justinschmitz97** [comment]
Can reproduce. Same bug happens on Chrome & Firefox.

**Comment by hyoretsu** [comment]
It seems to be a bug with Windows, it also disappears when I view it on my phone.

**Comment by hyoretsu** [comment]
Actually it's a bug with Windows, but encoding-wise. I've successfully converted some images without the bar, but most have it.

**Comment by hyoretsu** [comment]
It also happens when converting from Ubuntu, but it's a problem with Windows Gallery. ImageGlass displays it correctly.
