### ISSUE TITLE
Does avif really support GIFs?

### ISSUE THREAD

**Issue by you-hengh** [justinschmitz97/avif.io#101]
I have a gif dynamic picture, which I converted to avif format using the official website converter, but it becomes a static picture.

source:

![640](https://user-images.githubusercontent.com/34816426/205202031-c541766b-6db5-4922-bf25-ea0400afa54e.gif)

after:
issue don't support avif, emmmm,In short, the effect of the conversion is the same as that of a jpeg image.Do you understand what I mean?

So I want to ask, does avif really support gif?

**Comment by justinschmitz97** [comment]
Hey! Avif supports sequences when it comes to the .avifs format. Our converter is only capable of providing static .avif files.
You may search for a gif to avifs converter on google. :)

**Comment by you-hengh** [comment]
I have tried a lot of websites, but the results are not good. Can you recommend a website for me?
