### ISSUE TITLE
Add the option to disable the "fancy stuff" for slow-ass PCs...

### ISSUE THREAD

**Issue by gabriele2000** [justinschmitz97/avif.io#107]
...or simply because if you're using a weak GPU or CPU rendering for some reason, avif.io is slow as hell framerate-wise.

**Comment by justinschmitz97** [comment]
Please elaborate what exactly the fancy stuff is.

**Comment by gabriele2000** [comment]
Background animations, the animated squares... Somehow they're very taxing, especially the squares.

**Comment by justinschmitz97** [comment]
Done. Removed completly.
