### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tranquillity-codes** [justinschmitz97/avif.io#110]
There is no LICENSE.md file, no SPDX identifiers, no license headers and there are no mentions of a license in the README - is this project All Rights Reserved / Proprietary?

**Comment by justinschmitz97** [comment]
Seems to have been accidentally deleted in a merge. Feel free to use the source code for anything. :)

**Comment by justinschmitz97** [comment]
Or even feel free to add the right license as a PR

**Comment by tranquillity-codes** [comment]
I see, in that case is it public domain (Eg [Unlicense](https://unlicense.org/))? Copyfree (Eg BSD-2/3-clause, MIT)? I am happy to make a pull request :)

**Comment by justinschmitz97** [comment]
Sounds great. Feel free to create a PR! Thanks a ton.

**Comment by mon-jai** [comment]
Seems that no license file is added to the repo.

@justinschmitz97 did you close the issue by accident?
