### ISSUE TITLE
failed compress jpg to avif

### ISSUE THREAD

**Issue by 3xploiton3** [justinschmitz97/avif.io#114]
![image](https://github.com/justinschmitz97/avif.io/assets/19517680/80f974a0-52ed-4fc6-a64d-419be56e63d8)

source file:
https://mega.nz/folder/161AUCoT#p-G0415zPuk96OzEGvuKCg

**Comment by 3xploiton3** [comment]
conversion settings
![image](https://github.com/justinschmitz97/avif.io/assets/19517680/abc6801f-f2a2-454a-88c7-8d908ad42408)

**Comment by justinschmitz97** [comment]
That's not an issue.

**Comment by 3xploiton3** [comment]
why size got bigger? 
i do with avif-cli it worked properly
