### ISSUE TITLE
Too much of GPU usage due to all the fancy animations on the webpage.

### ISSUE THREAD

**Issue by rohitghali** [justinschmitz97/avif.io#117]
Firstly, it is a fantastic utility. Thanks for making one. But what's up with all those fancy animations? It is eating up all the gpu. Intel 620 is being used at around 80% when the webpage is shown on screen. Why not have a simpler website?

**Comment by justinschmitz97** [comment]
I don't experience any high GPU usage at all. Can you track down the issue, which elements exactly stress your GPU that much? Thank you.

**Comment by justinschmitz97** [comment]
e.g. background images, 3d animations, blurred backgrounds, etc.
I'm happy to work on the issue once I know where the root is. Thanks!

**Comment by justinschmitz97** [comment]
I have removed atropos, as it appearently took a lot of ressources.

**Comment by rohitghali** [comment]
Didn't make a difference. Still eats up almost 70% GPU.

**Comment by rohitghali** [comment]
[Firefox 2023-10-24 22.42 profile.json.gz](https://github.com/justinschmitz97/avif.io/files/13160816/Firefox.2023-10-24.22.42.profile.json.gz)

Check if this helps.

**Comment by justinschmitz97** [comment]
Unfortunately not. Feel free to check the source code in your dev tools and remove the div with the class 'mb-4 mt-12 hidden max-w-screen-lg overflow-hidden px-3 md:block' (inside <div id="__next">). Let me know if this changes a thing.

**Comment by justinschmitz97** [comment]
Until now, I can't reproduce your issue, not even on a 10 years old CPU/GPU.
