### ISSUE TITLE
Couple of mistakes on AVIF article

### ISSUE THREAD

**Issue by FrankGalligan** [justinschmitz97/avif.io#35]
- Max size of an AVIF image is 65536x65536. See https://aomediacodec.github.io/av1-avif/#profiles-overview
- Max size allowed in Chrome is 16K x 16K. I think Chrome restricts all image formats to a max size. But as you mention Chrome can handle bigger images with grid encoding.
- AVIF does support progressive decoding.
- I'm not sure JpegXL is faster at decoding single core or multi-core. Would be good to post your data or where you got the info.

Other than that nice website!

**Comment by justinschmitz97** [comment]
Please provide sources to each claim and the article in which you found wrong information. Thanks!

**Comment by FrankGalligan** [comment]
I already provided a link to the max size of an AVIF image. https://aomediacodec.github.io/av1-avif/#profiles-overview

Here is a link to the support of progressive images in AVIF spec: https://aomediacodec.github.io/av1-avif/#layered-items

As for the decoding comparison it was based off empirical data, but would love to see where you got your info. 

Thanks.

**Comment by justinschmitz97** [comment]
Thanks, fixing this in latest release!
