### ISSUE TITLE
Problems with created .avif files since latest Chrome update

### ISSUE THREAD

**Issue by Pamalosebi** [justinschmitz97/avif.io#36]
Hi,

the .avif files created with avif.io can't be opened since the latest Chrome update. But created with for e.g. GIMP does still work.

Here a simple comparison:

- Created with avif.io (as .zip since github doesn't alow .avif files):
[Outlook_icon_test.avif.zip](https://github.com/justinschmitz97/avif.io/files/6924423/Outlook_icon_test.avif.zip)
- And created with GIMP (as .zip since github doesn't alow .avif files):
[Outlook_icon_test_gimp.avif.zip](https://github.com/justinschmitz97/avif.io/files/6924438/Outlook_icon_test_gimp.avif.zip)

Can you have a look? Thank you a lot.

**Comment by justinschmitz97** [comment]
Hi, thanks for reporting! We are aware of this issue and trying to fix it, but no success for now. Do you have any idea?

**Comment by Pamalosebi** [comment]
Hey,
I am far away from being an expert... my first idea was to check both files in hex.
And I noticed some changes... which doesn't mean, that has anything to do with that issue.

avif generated with **gimp** - file header:
->
00000000  00 00 00 18 66 74 79 70  61 76 69 66 00 00 00 00  ....ftypavif....
00000010  61 76 69 66 6D 69 66 31  00 00 0D 1A 6D 65 74 61  avifmif1....meta
00000020  00 00 00 00 00 00 00 21  68 64 6C 72 00 00 00 00  .......!hdlr....
00000030  00 00 00 00 70 69 63 74  00 00 00 00 00 00 00 00  ....pict........
00000040  00 00 00 00 00 00 00 00  0E 70 69 74 6D 00 00 00  .........pitm...
00000050  00 00 01 00 00 00 22 69  6C 6F 63 00 00 00 00 44  ......"iloc....D
00000060  40 00 01 00 01 00 00 00  00 0D 3A 00 01 00 00 00  @.........:.....
00000070  00 00 07 5A FD 00 00 00  23 69 69 6E 66 00 00 00  ...Z....#iinf...
00000080  00 00 01 00 00 00 15 69  6E 66 65 02 00 00 00 00  .......infe.....
00000090  01 00 00 61 76 30 31 00  00 00 0C 9A 69 70 72 70  ...av01.....iprp
000000A0  00 00 0C 7C 69 70 63 6F  00 00 0C 54 63 6F 6C 72  ...|ipco...Tcolr
000000B0  70 72 6F 66 00 00 0C 48  4C 69 6E 6F 02 10 00 00  prof...HLino....
000000C0  6D 6E 74 72 52 47 42 20  58 59 5A 20 07 CE 00 02  mntrRGB XYZ ....
000000D0  00 09 00 06 00 31 00 00  61 63 73 70 4D 53 46 54  .....1..acspMSFT
000000E0  00 00 00 00 49 45 43 20  73 52 47 42 00 00 00 00  ....IEC sRGB....
000000F0  00 00 00 00 00 00 00 00  00 00 F6 D6 00 01 00 00  ................
00000100  00 00 D3 2D 48 50 20 20  00 00 00 00 00 00 00 00  ...-HP  ........
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000130  00 00 00 00 00 00 00 11  63 70 72 74 00 00 01 50  ........cprt...P
00000140  00 00 00 33 64 65 73 63  00 00 01 84 00 00 00 6C  ...3desc.......l
00000150  77 74 70 74 00 00 01 F0  00 00 00 14 62 6B 70 74  wtpt........bkpt
00000160  00 00 02 04 00 00 00 14  72 58 59 5A 00 00 02 18  ........rXYZ....
00000170  00 00 00 14 67 58 59 5A  00 00 02 2C 00 00 00 14  ....gXYZ...,....
00000180  62 58 59 5A 00 00 02 40  00 00 00 14 64 6D 6E 64  bXYZ...@....dmnd
00000190  00 00 02 54 00 00 00 70  64 6D 64 64 00 00 02 C4  ...T...pdmdd....
000001A0  00 00 00 88 76 75 65 64  00 00 03 4C 00 00 00 86  ....vued...L....
000001B0  76 69 65 77 00 00 03 D4  00 00 00 24 6C 75 6D 69  view.......$lumi
000001C0  00 00 03 F8 00 00 00 14  6D 65 61 73 00 00 04 0C  ........meas....
000001D0  00 00 00 24 74 65 63 68  00 00 04 30 00 00 00 0C  ...$tech...0....
000001E0  72 54 52 43 00 00 04 3C  00 00 08 0C 67 54 52 43  rTRC...<....gTRC
000001F0  00 00 04 3C 00 00 08 0C  62 54 52 43 00 00 04 3C  ...<....bTRC...<
00000200  00 00 08 0C 74 65 78 74  00 00 00 00 43 6F 70 79  ....text....Copy
00000210  72 69 67 68 74 20 28 63  29 20 31 39 39 38 20 48  right (c) 1998 H
00000220  65 77 6C 65 74 74 2D 50  61 63 6B 61 72 64 20 43  ewlett-Packard C
00000230  6F 6D 70 61 6E 79 00 00  64 65 73 63 00 00 00 00  ompany..desc....
00000240  00 00 00 12 73 52 47 42  20 49 45 43 36 31 39 36  ....sRGB IEC6196
00000250  36 2D 32 2E 31 00 00 00  00 00 00 00 00 00 00 00  6-2.1...........
00000260  12 73 52 47 42 20 49 45  43 36 31 39 36 36 2D 32  .sRGB IEC61966-2
00000270  2E 31 00 00 00 00 00 00  00 00 00 00 00 00 00 00  .1..............
00000280  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000290  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000002A0  00 00 00 00 58 59 5A 20  00 00 00 00 00 00 F3 51  ....XYZ .......Q
000002B0  00 01 00 00 00 01 16 CC  58 59 5A 20 00 00 00 00  ........XYZ ....
000002C0  00 00 00 00 00 00 00 00  00 00 00 00 58 59 5A 20  ............XYZ 
000002D0  00 00 00 00 00 00 6F A2  00 00 38 F5 00 00 03 90  ......o...8.....
000002E0  58 59 5A 20 00 00 00 00  00 00 62 99 00 00 B7 85  XYZ ......b.....
000002F0  00 00 18 DA 58 59 5A 20  00 00 00 00 00 00 24 A0  ....XYZ ......$.
00000300  00 00 0F 84 00 00 B6 CF  64 65 73 63 00 00 00 00  ........desc....
00000310  00 00 00 16 49 45 43 20  68 74 74 70 3A 2F 2F 77  ....IEC http://w
00000320  77 77 2E 69 65 63 2E 63  68 00 00 00 00 00 00 00  ww.iec.ch.......
00000330  00 00 00 00 16 49 45 43  20 68 74 74 70 3A 2F 2F  .....IEC http://
00000340  77 77 77 2E 69 65 63 2E  63 68 00 00 00 00 00 00  www.iec.ch......
00000350  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000360  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000370  00 00 00 00 00 00 00 00  64 65 73 63 00 00 00 00  ........desc....
00000380  00 00 00 2E 49 45 43 20  36 31 39 36 36 2D 32 2E  ....IEC 61966-2.
00000390  31 20 44 65 66 61 75 6C  74 20 52 47 42 20 63 6F  1 Default RGB co
000003A0  6C 6F 75 72 20 73 70 61  63 65 20 2D 20 73 52 47  lour space - sRG
000003B0  42 00 00 00 00 00 00 00  00 00 00 00 2E 49 45 43  B............IEC
000003C0  20 36 31 39 36 36 2D 32  2E 31 20 44 65 66 61 75   61966-2.1 Defau
000003D0  6C 74 20 52 47 42 20 63  6F 6C 6F 75 72 20 73 70  lt RGB colour sp
000003E0  61 63 65 20 2D 20 73 52  47 42 00 00 00 00 00 00  ace - sRGB......
000003F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000400  64 65 73 63 00 00 00 00  00 00 00 2C 52 65 66 65  desc.......,Refe
00000410  72 65 6E 63 65 20 56 69  65 77 69 6E 67 20 43 6F  rence Viewing Co
00000420  6E 64 69 74 69 6F 6E 20  69 6E 20 49 45 43 36 31  ndition in IEC61
00000430  39 36 36 2D 32 2E 31 00  00 00 00 00 00 00 00 00  966-2.1.........
00000440  00 00 2C 52 65 66 65 72  65 6E 63 65 20 56 69 65  ..,Reference Vie
00000450  77 69 6E 67 20 43 6F 6E  64 69 74 69 6F 6E 20 69  wing Condition i
00000460  6E 20 49 45 43 36 31 39  36 36 2D 32 2E 31 00 00  n IEC61966-2.1..
00000470  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000480  00 00 00 00 00 00 00 00  76 69 65 77 00 00 00 00  ........view....
00000490  00 13 A4 FE 00 14 5F 2E  00 10 CF 14 00 03 ED CC  ......_.........
000004A0  00 04 13 0B 00 03 5C 9E  00 00 00 01 58 59 5A 20  ......\.....XYZ 
000004B0  00 00 00 00 00 4C 09 56  00 50 00 00 00 57 1F E7  .....L.V.P...W..
000004C0  6D 65 61 73 00 00 00 00  00 00 00 01 00 00 00 00  meas............
000004D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 02 8F  ................
000004E0  00 00 00 02 73 69 67 20  00 00 00 00 43 52 54 20  ....sig ....CRT 
000004F0  63 75 72 76 00 00 00 00  00 00 04 00 00 00 00 05  curv............
00000500  00 0A 00 0F 00 14 00 19  00 1E 00 23 00 28 00 2D  ...........#.(.-
00000510  00 32 00 37 00 3B 00 40  00 45 00 4A 00 4F 00 54  .2.7.;.@.E.J.O.T
00000520  00 59 00 5E 00 63 00 68  00 6D 00 72 00 77 00 7C  .Y.^.c.h.m.r.w.|
00000530  00 81 00 86 00 8B 00 90  00 95 00 9A 00 9F 00 A4  ................
00000540  00 A9 00 AE 00 B2 00 B7  00 BC 00 C1 00 C6 00 CB  ................
00000550  00 D0 00 D5 00 DB 00 E0  00 E5 00 EB 00 F0 00 F6  ................
00000560  00

avif generated with **avif.io** - file header:
->
00000000  00 00 00 14 66 74 79 70  61 76 69 66 00 00 00 00  ....ftypavif....
00000010  6D 69 66 31 00 00 01 26  6D 65 74 61 00 00 00 00  mif1...&meta....
00000020  00 00 00 0E 70 69 74 6D  00 00 00 00 00 01 00 00  ....pitm........
00000030  00 2C 69 6C 6F 63 00 00  00 00 44 00 00 02 00 01  .,iloc....D.....
00000040  00 00 00 01 00 00 01 95  00 05 C8 93 00 02 00 00  ................
00000050  00 01 00 00 01 42 00 00  00 53 00 00 00 38 69 69  .....B...S...8ii
00000060  6E 66 00 00 00 00 00 02  00 00 00 15 69 6E 66 65  nf..........infe
00000070  02 00 00 00 00 01 00 00  61 76 30 31 00 00 00 00  ........av01....
00000080  15 69 6E 66 65 02 00 00  00 00 02 00 00 61 76 30  .infe........av0
00000090  31 00 00 00 00 1A 69 72  65 66 00 00 00 00 00 00  1.....iref......
000000A0  00 0E 61 75 78 6C 00 02  00 01 00 01 00 00 00 8E  ..auxl..........
000000B0  69 70 72 70 00 00 00 6C  69 70 63 6F 00 00 00 14  iprp...lipco....
000000C0  69 73 70 65 00 00 00 00  00 00 07 21 00 00 0A B3  ispe.......!....
000000D0  00 00 00 0C 61 76 31 43  81 00 00 00 00 00 00 0C  ....av1C........
000000E0  61 76 31 43 81 00 08 00  00 00 00 38 61 75 78 43  av1C.......8auxC
000000F0  00 00 00 00 75 72 6E 3A  6D 70 65 67 3A 6D 70 65  ....urn:mpeg:mpe
00000100  67 42 3A 63 69 63 70 3A  73 79 73 74 65 6D 73 3A  gB:cicp:systems:
00000110  61 75 78 69 6C 69 61 72  79 3A 61 6C 70 68 61 00  auxiliary:alpha.
00000120  00 00 00 1A 69 70 6D 61  00 00 00 00 00 00 00 02  ....ipma........
00000130  00

The GIMP-file gets announced with "avifmif1" while the avif.io-file has there "mif1".
And so on...

Again, I am not an expert. But maybe that has something to do with it?

**Comment by justinschmitz97** [comment]
Fixed!
