### ISSUE TITLE
Content: Typo in Quality and Limits section of webp comparison

### ISSUE THREAD

**Issue by Taywee** [justinschmitz97/avif.io#51]
In [Quality and limits](https://avif.io/blog/comparisons/avif-vs-webp/#qualityandlimits), it is claimed that:

> AVIF has an image resolution limit of 65536 x 65536 pixels.

> WebP also has a hard limit to an image's frame size, with its maximum dimension being 16,383 x 16,383. While this is an improvement over AVIF,

I don't see how 16k by 16k is an improvement over 64k by 64k.  Is this a typo?

**Comment by justinschmitz97** [comment]
You're completely right! We have change the pixel count in the past and likely forgot to check if the surrounding claims still make sense. Thanks for pointing out! Found this error on our BMP article as well. Will fix ASAP.

**Comment by justinschmitz97** [comment]
Fixed with 59f0fd6ba5a3a7ec4b5ec3f918ec9287f41836f5
