### ISSUE TITLE
Use case for mp4 to animated AVIF

### ISSUE THREAD

**Issue by dylannirvana** [justinschmitz97/avif.io#58]
We have (thus far) an unusual use-case, taking mp4 videos and converting them to _animated_ AVIF. Your interface does not seem to allow this or even accept mp4.

The only resource I found that does this is EZGif https://ezgif.com/video-to-avif. As far as I know, no one has made a script available. Obviously, it would be better to do this programmatically via an npm module. ffmpeg has code appropriate for animated WEBP but not AVIF. 

This is one such use-case https://www.bmi.com/award-shows/london-2021/

Considering where the future is headed, AVIF may become very popular. And this may become a very useful script to have.

**Comment by justinschmitz97** [comment]
You can use a <video> tag with different sources for different devices and formats, just like with the picture tag.

**Comment by dylannirvana** [comment]
That makes sense, using a <video> tag for the source set. My understanding however, is AVIF(S) is the implementation specifically for AV1.

**Comment by justinschmitz97** [comment]
Makes sense, even though I don't see the use case switching between animated and non-animated images for the viewer, especially when multi-device is used and the experience is different for no obvious reason.

Despite that sequence support would be awesome, we can't offer this in the next 12 months. The development takes too much effort.
