### ISSUE TITLE
CSS Tutorial will download both images: Avif and JPG when avif is supported

### ISSUE THREAD

**Issue by hsusteph5** [justinschmitz97/avif.io#74]
Hi,

Following this CSS [blog](https://avif.io/blog/tutorials/css/) and noticed that this solution will download both jpg and avif if the browser supports avif, since the `img` class will always be applied.

```
/* Simple approach */
.img { background-image: url('avif-in-css.jpg') }
.webp .img { background-image: url('avif-in-css.webp') }
.avif .img { background-image: url('avif-in-css.avif') }
```

Using Chrome, both `jpg` version and the `avif` version will be downloaded over the network.
See example [here](https://codesandbox.io/s/elastic-dijkstra-iofmz)

Thoughts on changing the AVIF support detection script to support checking WEBP and then adding a fallback class when both avif and webp are false.
Sample [code](https://codesandbox.io/s/fxrho?file=/src/index.js)

**Comment by justinschmitz97** [comment]
You're right. Thank you so much! I have updated the tutorial with your code and added an update note at the bottom of the article.
