### ISSUE TITLE
SBOX_FATAL_MEMORY_EXCEEDED when processing a batch of high res images

### ISSUE THREAD

**Issue by KinIcy** [justinschmitz97/avif.io#76]
Hello, 

I just tried to convert a batch of ~100 images of 4000x6000 jpeg. avif.io loads all of them and starts working on 8 at the time. Soon after the first ones get converted, Chrome crashes with SBOX_FATAL_MEMORY_EXCEEDED error.  I noticed the sites start to use a huge amount of ram as soon as it finishes the first conversions,

Chrome version: Version 97.0.4692.71
Chrome uses about 8GB of ram and then crashes. Firefox stays around 8GB and completes the job correctly.

I just noticed the site is using the whole image as the thumbnail of the download button. That is probably what is making it use too much RAM.

**Comment by justinschmitz97** [comment]
I don't think background images are the problem here. I'll look into it.

**Comment by justinschmitz97** [comment]
Could you provide some example images?

**Comment by justinschmitz97** [comment]
I've changed some code and stress-tested with 250 images of 4k size, which worked great.
Please let me know if you still experience issues.

**Comment by KinIcy** [comment]
@justinschmitz97 I just tested again, still happening.

Test image: https://images.wallpaperscraft.com/image/single/road_mountains_trees_163008_4000x6000.jpg
![road_mountains_trees_163008_4000x6000](https://user-images.githubusercontent.com/10891866/149671355-5256c7e3-e719-4f73-9f8d-5a1e2bcbaea2.jpg)

I duplicated the images about 15 times, and then added them all at once, tab crashed after a few seconds.

**Comment by justinschmitz97** [comment]
Not solvable. Consider using a local processor.
