### ISSUE TITLE
Feature Request: Image Comparison

### ISSUE THREAD

**Issue by dekdevy** [justinschmitz97/avif.io#86]
Hello,

Hope its okay to make requests here, if not feel free to ignore / close.

I recently found out about this format through your website, and it got me very interested. I figured i'd test a few images (this is how I suppose most people will use the page) and then I dragged the image back onto my desktop.. only to drag them back into the browser as nothing other than my browser can open them, to compare them with the original uploaded. 
What about streamlining this process so people can explore the quality of the format and its compression settings? Put the original next to the compressed image after uploading (or hidden behind a button). Even better, put them on top of another and let the user move a line over the image that blends from the original to the compressed image, making any difference noticeable. (The tech is already there on the bottom of the page with the default images, which is excellent!)
To me, this would have been super useful.

I might be able to contribute to this myself, however unfortunately not at this time. Is this something the maintainers would be interested in?

**Comment by justinschmitz97** [comment]
Hey! 

I love the idea of a direct comparison to explore the format. Essentially, you are requesting the functionality of squoosh.app, which I love as well! Unfortunately, we currently don't have any development capabilities. I run this project on my spare time as a non-dev. If you ever happen to be able to contribute to this yourself, please get in touch. Thanks. :)
